# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [302]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [303]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [304]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [305]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x242e52a58d0
byteorder:  little
byteswap:  False
type: int32


In [306]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [307]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [308]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [309]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.89247745 0.91500066 0.78303575]
 [0.01808254 0.97310139 0.20930378]
 [0.69683949 0.40507397 0.07791492]]


In [310]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [311]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.89247745 0.91500066 0.78303575]
 [0.01808254 0.97310139 0.20930378]
 [0.69683949 0.40507397 0.07791492]]
...
float64
(3, 3)
3
2
9
8
72


In [312]:
arr.__sizeof__()

192

### ЗАВДАННЯ 1

In [313]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.random.rand(3, 4)
print(arr1_1)

[[0.9785182  0.76327628 0.91213002 0.62352999]
 [0.74298271 0.99557356 0.47349683 0.20815724]
 [0.9203698  0.14730451 0.65296986 0.47075049]]


In [314]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(['A', 'B', 'C', 'D', 'E', 'F'])
print(arr1_2)

['A' 'B' 'C' 'D' 'E' 'F']


In [315]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.arange(1.1, 2, 0.1)
print(arr1_3)

[1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [316]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [317]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [318]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [319]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [320]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.zeros((3,1,3))

print(arr2_1)

[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]


In [321]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3,3))
print(arr2_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [322]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2).reshape((2,3))

print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [323]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [324]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[49 22 41 41]
 [17 31 41 17]
 [23 16 43 30]
 [49 43 47 26]]


In [325]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

17


In [326]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[49 43 47 26]


In [327]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[49 22 41 41]
 [17 31 41 17]]


In [328]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[22 41]
 [31 41]
 [16 43]
 [43 47]]


In [329]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[49 22 41 41]
 [23 16 43 30]]


In [330]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[49 22 41 41 31 41 23 43 30 49 43 47 26]


### ЗАВДАННЯ 3

In [331]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10, 100, (4,5))
print(arr3_1)

[[57 25 14 66 65]
 [27 86 43 19 33]
 [20 61 70 86 47]
 [26 84 72 53 28]]


In [332]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1][2]
print(el3_2)

43


In [333]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[27 86 43 19 33]


In [334]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4, 2]
print(vect3_4)

[14 43 70 72]


In [335]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`

# Не зовсім зрозуміло як вивести матрицю з 2 та 3 рядка та 2 та 3 колонки, оскільки в рядку 5 елементів а у колонці 4.
# Тобто, у нас буде 2 масиви матриці з 5 елементами, та 2 масиви з 4 елементами.

print(arr3_1[1:3][0]) # 2 ряд
print(arr3_1[1:3][1]) # 3 ряд
print(arr3_1[0:4, 1]) # 2 колонка 
print(arr3_1[0:4, 2]) # 3 колонка
print()

# Скоріш за все, це воно.
mat3_5 = np.array([[arr3_1[1:3][0][1],arr3_1[1:3][0][2]],[arr3_1[1:3][1][1], arr3_1[1:3][1][2]]])

print(mat3_5)


[27 86 43 19 33]
[20 61 70 86 47]
[25 86 61 84]
[14 43 70 72]

[[86 43]
 [61 70]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [336]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [337]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [338]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.44982195 0.30617067 0.13869801 0.42353133 0.15734064]
 [0.04826262 0.43675607 0.5045201  0.93811487 0.85313024]
 [0.92942685 0.32410963 0.56781549 0.39942433 0.84448741]
 [0.59858321 0.93995576 0.67070697 0.99237847 0.1177466 ]
 [0.62100073 0.88053863 0.23091382 0.14093116 0.40822779]]
...
[0.44982195 0.43675607 0.56781549 0.99237847 0.40822779]


In [339]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.44982195 0.04826262 0.92942685 0.59858321 0.62100073]
 [0.30617067 0.43675607 0.32410963 0.93995576 0.88053863]
 [0.13869801 0.5045201  0.56781549 0.67070697 0.23091382]
 [0.42353133 0.93811487 0.39942433 0.99237847 0.14093116]
 [0.15734064 0.85313024 0.84448741 0.1177466  0.40822779]]


In [340]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.15332067318132558


In [341]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[ 1.64548734 -0.75350422  0.58055503 -0.1946138  -0.20434939]
 [-0.47866664  0.1858468  -0.76419598  0.14664427  1.33466957]
 [-4.21405606 -0.49608795  1.3888685   1.81283207 -0.73504759]
 [ 2.29461951  0.51303543 -0.58663876 -0.11988659 -0.70842227]
 [ 0.12085416  0.84886986  0.18211826 -1.00429922  0.54196314]]


### ЗАВАДАННЯ 4

In [342]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200

step = np.linspace(100,200,36, retstep=True)[1]-0.001

mat4_1 = np.around(np.arange(100,200,step).reshape((6,6)))

print(mat4_1)

[[100. 103. 106. 109. 111. 114.]
 [117. 120. 123. 126. 129. 131.]
 [134. 137. 140. 143. 146. 149.]
 [151. 154. 157. 160. 163. 166.]
 [169. 171. 174. 177. 180. 183.]
 [186. 189. 191. 194. 197. 200.]]


In [343]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diagonal(mat4_1)
print(diag4_2)

[100. 120. 140. 160. 180. 200.]


In [344]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[100. 117. 134. 151. 169. 186.]
 [103. 120. 137. 154. 171. 189.]
 [106. 123. 140. 157. 174. 191.]
 [109. 126. 143. 160. 177. 194.]
 [111. 129. 146. 163. 180. 197.]
 [114. 131. 149. 166. 183. 200.]]


In [345]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)

## 5. Операції над масивами

### ПРИКЛАДИ

In [346]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [347]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [348]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [349]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [350]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [351]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [352]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [353]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [354]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\Acer\AppData\Local\Temp\ipykernel_17564\3347190385.py:2: RuntimeWarning: divide by zero encountered in true_divide
  K = N / M


In [355]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [356]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [357]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [358]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [359]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [360]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[8 4 6 2 2]
[8 4 6 2 2]
2486369426576 2486369426576
[8 4 6 2 2]
2486369426576 2486369750448


In [361]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [362]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(10, 20, (3,4))
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[18 18 16 14]
 [18 16 19 14]
 [14 15 15 13]]
[66 67 57]


In [363]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = min(sum_mat5_1)
print(min_mat5_1)

57


In [364]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[118 118 116 114]
 [118 116 119 114]
 [114 115 115 113]]


In [365]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
diag = np.diagonal(mat5_3)
mat5_4 = np.dot(diag, mat5_1)
print(mat5_4)

[5822 5705 5817 4771]


In [366]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.vstack([mat5_3, mat5_4])
print(mat5_5)

[[ 118  118  116  114]
 [ 118  116  119  114]
 [ 114  115  115  113]
 [5822 5705 5817 4771]]
