#  Лабораторна робота "Обробка табличних даних засобами бібліотеки Pandas"

__Метою__ лабораторної роботи є вивчення технологій первинного аналізу даних в середовищі бібліотеки Pandas, а саме здобуття навичок:
- працювати з даними використовуючи мову Python та пакет Pandas
- робити передобробку даних
- знаходити прості закономірності у даних

In [1]:
# підключити бібліотеки Pandas та NumPy
import pandas as pd
import numpy as np

## 1. Створення  DataFrame

__DataFrame__ — це двовимірна неоднорідна таблична структура даних із змінюваними розмірами з іменованими вісями (рядками та стовпцями)

### ПРИКЛАДИ

In [2]:
# створити DataFrame з 1 колонкою з python-списка
df = pd.DataFrame(["Петя", "Вася", "Микола"])
print(df)
print(type(df))

        0
0    Петя
1    Вася
2  Микола
<class 'pandas.core.frame.DataFrame'>


In [3]:
# створити DataFrame з np-матриці розміром 10х10 випадкових чисел
mat = np.random.randint(100, 500, (10,10), dtype="int16")
print(mat)
df = pd.DataFrame(mat)
df

[[392 245 408 220 298 429 453 474 358 406]
 [495 412 419 176 300 332 123 276 196 172]
 [351 204 363 286 323 350 161 412 225 451]
 [188 319 193 301 304 377 327 491 341 314]
 [151 415 454 298 475 426 232 252 148 121]
 [457 398 140 248 145 324 257 365 304 293]
 [322 108 111 478 479 366 142 249 153 382]
 [475 350 356 288 288 262 184 428 344 171]
 [374 477 453 329 309 443 349 289 383 451]
 [223 204 464 132 485 390 492 351 201 379]]


0    1    2    3    4    5    6    7    8    9
0  392  245  408  220  298  429  453  474  358  406
1  495  412  419  176  300  332  123  276  196  172
2  351  204  363  286  323  350  161  412  225  451
3  188  319  193  301  304  377  327  491  341  314
4  151  415  454  298  475  426  232  252  148  121
5  457  398  140  248  145  324  257  365  304  293
6  322  108  111  478  479  366  142  249  153  382
7  475  350  356  288  288  262  184  428  344  171
8  374  477  453  329  309  443  349  289  383  451
9  223  204  464  132  485  390  492  351  201  379

In [4]:
# створити DataFrame з 2-мірного випадкового масиву з іменованими колонками
arr = np.random.random((5,3))
print(arr)
df = pd.DataFrame(arr, columns=["колонка 1", "колонка 2", "колонка 3"])
df

[[0.9448068  0.83955796 0.68419372]
 [0.22143291 0.23047233 0.47794322]
 [0.10030188 0.35772573 0.84457077]
 [0.75856735 0.09227705 0.70929122]
 [0.7845517  0.37278635 0.94432824]]


колонка 1  колонка 2  колонка 3
0   0.944807   0.839558   0.684194
1   0.221433   0.230472   0.477943
2   0.100302   0.357726   0.844571
3   0.758567   0.092277   0.709291
4   0.784552   0.372786   0.944328

In [18]:
# створити DataFrame з python-словника в якому ключ - це ім'я, а значення - 
# це масив з 5-ти випадкових чисел з модифікованими індексами рядків
d = {
    "Петя": np.random.random(5),
    "Вася" : np.random.random(5),
    "Микола":np.random.random(5)
    }
a = pd.DataFrame(d, index=[10,20,30,40,50])

In [19]:
a

Петя      Вася    Микола
10  0.836907  0.195855  0.860988
20  0.325348  0.988914  0.238220
30  0.129564  0.685394  0.936427
40  0.317217  0.767520  0.908531
50  0.549039  0.048989  0.077559

In [17]:
# створити dataFrame з ітеруємого об'єкта
name = ["Вася", "Петя", "Микола"]
rik = [2001, 2000, 2003]
name_rik = list(zip(name, rik))
print(name_rik)
df = pd.DataFrame(name_rik, columns=["Ім'я", "Рік народження"])
df

[('Вася', 2001), ('Петя', 2000), ('Микола', 2003)]


Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

In [8]:
str(name_rik[2])

"('Микола', 2003)"

In [9]:
pd.read_csv?

In [10]:
!echo "Вася, 2001\nПетя, 2000,\nМикола,2003\n" > file.csv
!cat file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv("file.csv", names=["Ім'я", "Рік народження"])
df

"cat" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.


UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 1: invalid continuation byte

### ЗАВДАННЯ

In [11]:
# ЗАВДАННЯ 1.1: створити датафрейм з списку 10-ти простих чисел
df1_1 = pd.DataFrame([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(df1_1)

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10


In [12]:
# ЗАВДАННЯ 1.2: створити датафрейм з матриці 5х6 випадкових чисел з плаваючою точкою
df1_2 = np.random.random((5,6))
print(df1_2)

[[0.75358776 0.31796079 0.33496651 0.86871993 0.60196289 0.76747599]
 [0.94844209 0.47100663 0.2296953  0.96659356 0.42414065 0.28615852]
 [0.71905446 0.82794333 0.87990383 0.10574085 0.87588425 0.53162643]
 [0.50635891 0.46845137 0.63683795 0.14407366 0.7743007  0.54963602]
 [0.28832351 0.63210161 0.36820482 0.22522485 0.22694418 0.65798557]]


ЗАВДАННЯ 1.3: створити  DataFrame наступного вигляду:

|ім'я | прізвище| рік народження | телефон
|:-----|:------|:-----:|:-------:
|Петро| Петров| 2000| 222-222-2222
|Іван| Іванов| 2002| 333-333-3333
|Степан| Степанов| 2001| 444-444-4444

In [29]:
l = {
    "Ім'я": ["Петро", "Іван", "Степан"],
    "Прізвище" : ["Петров", "Іванов", "Степанов"],
    "Рік народження": ["2000", "2002", "2001"],
    "Телефон": ["222-222-2222", "333-333-3333", "444-444-4444"]
    }
df1_3 = pd.DataFrame(l)
df1_3

Ім'я  Прізвище Рік народження       Телефон
0   Петро    Петров           2000  222-222-2222
1    Іван    Іванов           2002  333-333-3333
2  Степан  Степанов           2001  444-444-4444

In [37]:
# ЗАВДАННЯ 1.4: створити датафрейм з 20 перших рядків excel-файлу, 
# який розташовано за адресою:

# HTTP Error 404: Not Found
url =  "https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls"


df1_4 = pd.read_excel(url)
df1_4 = df1_4.head(20)
print()

HTTPError: HTTP Error 404: Not Found

## 2. Інспектування DataFrame

__Інспектування__ - це процедури вивчення внутрішньої структури даних та вмісту датафрейма

### ПРИКЛАДИ

In [38]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [39]:
# отримати загальну інформацію про датасет
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [40]:
# вивести перші 3 рядкі
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [41]:
# вивести останні 2 рядки
titanic.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

In [42]:
# отримати імена колонок
col_names = titanic.columns
print(col_names)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [43]:
# вивести загальну статистику датасету - числові поля
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [44]:
# вивести статитсику текстового поля `Sex` 
titanic['Sex'].describe()

count      891
unique       2
top       male
freq       577
Name: Sex, dtype: object

In [45]:
# перевірити тип колонки датасету
type(titanic['Age'])

pandas.core.series.Series

In [46]:
# вивести перші 10 рядків деяких колонок
cols = ["Name", "Age", "Sex"]
titanic[cols].head(10)

Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male
5                                   Moran, Mr. James   NaN    male
6                            McCarthy, Mr. Timothy J  54.0    male
7                     Palsson, Master. Gosta Leonard   2.0    male
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0  female

In [47]:
# вивести рядки з 100 по 110
titanic[100:110]

PassengerId  Survived  Pclass                              Name     Sex  \
100          101         0       3           Petranec, Miss. Matilda  female   
101          102         0       3  Petroff, Mr. Pastcho ("Pentcho")    male   
102          103         0       1         White, Mr. Richard Frasar    male   
103          104         0       3        Johansson, Mr. Gustaf Joel    male   
104          105         0       3    Gustafsson, Mr. Anders Vilhelm    male   
105          106         0       3             Mionoff, Mr. Stoytcho    male   
106          107         1       3  Salkjelsvik, Miss. Anna Kristine  female   
107          108         1       3            Moss, Mr. Albert Johan    male   
108          109         0       3                   Rekic, Mr. Tido    male   
109          110         1       3               Moran, Miss. Bertha  female   

      Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
100  28.0      0      0   349245   7.8958   NaN        S  
101   NaN      0      0   349215   7.8958   NaN        S  
102  21.0      0      1    35281  77.2875   D26        S  
103  33.0      0      0     7540   8.6542   NaN        S  
104  37.0      2      0  3101276   7.9250   NaN        S  
105  28.0      0      0   349207   7.8958   NaN        S  
106  21.0      0      0   343120   7.6500   NaN        S  
107   NaN      0      0   312991   7.7750   NaN        S  
108  38.0      0      0   349249   7.8958   NaN        S  
109   NaN      1      0   371110  24.1500   NaN        Q

In [48]:
# вивести тільки чоловіків
cond = titanic["Sex"] == "male"
titanic[cond]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[577 rows x 12 columns]

In [49]:
# вивести рядки в яких пропущено значення поля `Age`
cond = titanic['Age'].isna()
titanic[cond].head(3)

PassengerId  Survived  Pclass                          Name     Sex  Age  \
5             6         0       3              Moran, Mr. James    male  NaN   
17           18         1       2  Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3       Masselmani, Mrs. Fatima  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583   NaN        Q  
17      0      0  244373  13.0000   NaN        S  
19      0      0    2649   7.2250   NaN        C

In [50]:
# вивести рядки з пасажирами вік яких з 30 до 50 років
cond = titanic['Age'].between(30, 50)
titanic[cond]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
13            14         0       3   
18            19         0       3   
..           ...       ...     ...   
872          873         0       1   
873          874         0       3   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
..                                                 ...     ...   ...    ...   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
4        0    373450   8.0500          NaN        S  
13       5    347082  31.2750          NaN        S  
18       0    345763  18.0000          NaN        S  
..     ...       ...      ...          ...      ...  
872      0       695   5.0000  B51 B53 B55        S  
873      0    345765   9.0000          NaN        S  
881      0    349257   7.8958          NaN        S  
885      5    382652  29.1250          NaN        Q  
890      0    370376   7.7500          NaN        Q  

[266 rows x 12 columns]

### ЗАВДАННЯ

In [57]:
# ЗАВДАННЯ 2.1: вивести характеристики датасету `titanic`
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [61]:
# ЗАВДАННЯ 2.2: вивести статистичні параметри полів `Age` та `Fare` датасету `titanic`
print(titanic['Age'].describe())
print()
print(titanic['Fare'].describe())

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64


In [68]:
# ЗАВДАННЯ 2.3: пірахувати кількість записів в яких заповнені усі показчики
not_na = titanic.notna().sum()
not_na

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [74]:
# ЗАВДАННЯ 2.4: пірахувати кількість виживших (survived=1) пасажирів жиночої статі (Sex=`female`)
len(titanic.loc[((titanic["Survived"] == 1) & (titanic["Sex"] == "female"))])

233

## 3. Перетворення датафреймів

__Перетворення__ - це сукупність операцій та методів для зміни структури та вмісту датафрейму та окремих його елементів

### ПРИКЛАДИ

In [75]:
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}

df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [76]:
# типи колонок та елементів в колонці
print(df["рейтинг"].dtype)
print(type(df['рейтинг']))

object
<class 'pandas.core.series.Series'>


In [77]:
# Перетворити тип колонки (показчика) 'рейтинг' в ціле числове
df['рейтинг'] = df['рейтинг'].astype("int8")
print(df["рейтинг"].dtype)

int8


In [78]:
# додати колонку "адреса"
df["адреса"] = ["Київ", "Бровари", "Фастів"]
df

ім'я  вік  рейтинг   адреса
0  Петя   22       10     Київ
1  Вася  200        3  Бровари
2  Галя   21        2   Фастів

In [79]:
#  збільшити значення "рейтинг" на 3
df['рейтинг'] = df['рейтинг'] + 3
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася  200        6  Бровари
2  Галя   21        5   Фастів

In [80]:
# виправити значення параметру 'вік' для імені 'Вася'
df.loc[1, "вік"] = 20
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася   20        6  Бровари
2  Галя   21        5   Фастів

In [81]:
# видалити колонку `вік'
df.drop(columns='вік', inplace=True)
df

ім'я  рейтинг   адреса
0  Петя       13     Київ
1  Вася        6  Бровари
2  Галя        5   Фастів

In [82]:
# вивести 5 перших рядків датафрейму
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [83]:
# вивести 3 випадкових рядки датафрейму
titanic.sample(3)

PassengerId  Survived  Pclass               Name   Sex   Age  SibSp  \
509          510         1       3     Lang, Mr. Fang  male  26.0      0   
687          688         0       3  Dakic, Mr. Branko  male  19.0      0   
521          522         0       3    Vovk, Mr. Janko  male  22.0      0   

     Parch  Ticket     Fare Cabin Embarked  
509      0    1601  56.4958   NaN        S  
687      0  349228  10.1708   NaN        S  
521      0  349252   7.8958   NaN        S

In [84]:
# відсортувати dataframe `titanic` за віком пасажиров
titanic.sort_values('Age')

PassengerId  Survived  Pclass                                      Name  \
803          804         1       3           Thomas, Master. Assad Alexander   
755          756         1       2                 Hamalainen, Master. Viljo   
644          645         1       3                    Baclini, Miss. Eugenie   
469          470         1       3             Baclini, Miss. Helene Barbara   
78            79         1       2             Caldwell, Master. Alden Gates   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
803    male  0.42      0      1        2625   8.5167   NaN        C  
755    male  0.67      1      1      250649  14.5000   NaN        S  
644  female  0.75      2      1        2666  19.2583   NaN        C  
469  female  0.75      2      1        2666  19.2583   NaN        C  
78     male  0.83      0      2      248738  29.0000   NaN        S  
..      ...   ...    ...    ...         ...      ...   ...      ...  
859    male   NaN      0      0        2629   7.2292   NaN        C  
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male   NaN      0      0      345777   9.5000   NaN        S  
878    male   NaN      0      0      349217   7.8958   NaN        S  
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S  

[891 rows x 12 columns]

In [85]:
# перейменувати значення в `Embarked` стовпчику:
# С - Cherbourg
# Q - Queenstown
# S - Southampton
titanic['Embarked'].replace({"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"},
                           inplace=True)
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin     Embarked  
0        0         A/5 21171   7.2500   NaN  Southampton  
1        0          PC 17599  71.2833   C85    Cherbourg  
2        0  STON/O2. 3101282   7.9250   NaN  Southampton  
3        0            113803  53.1000  C123  Southampton  
4        0            373450   8.0500   NaN  Southampton  
..     ...               ...      ...   ...          ...  
886      0            211536  13.0000   NaN  Southampton  
887      0            112053  30.0000   B42  Southampton  
888      2        W./C. 6607  23.4500   NaN  Southampton  
889      0            111369  30.0000  C148    Cherbourg  
890      0            370376   7.7500   NaN   Queenstown  

[891 rows x 12 columns]

In [141]:
# підрахувати кількість пасажирів 1-го класу (Pclass=1)
cond = titanic['Pclass'] == 1
kol_pass = titanic[cond]['PassengerId'].count()
kol_pass

184

In [142]:
# замінити відсутні номери кают на ''
titanic.fillna({"Cabin": "***"}, inplace=True)
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket  Fare Cabin     Embarked  
0      0         A/5 21171    26   ***  Southampton  
1      0          PC 17599    26   C85    Cherbourg  
2      0  STON/O2. 3101282    26   ***  Southampton

In [143]:
# видалити рядки в яких є відсутні значення 
titanic.dropna(axis=0, how='any', inplace=True)
titanic.shape

(712, 12)

### ЗАВДАННЯ

In [144]:
# ЗАВДАННЯ 3.1: створити датафрейм з словника d
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}
df = pd.DataFrame(d)
print(df)

   ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2


In [145]:
# ЗАВДАННЯ 3.2: додати до `df` стовбчик з показчиком 
# `рік завершення школи` = [2018, 2020, 200]
df["рік завершення школи"] = [2018, 2020, 200]
print(df)

   ім'я  вік рейтинг  рік завершення школи
0  Петя   22      10                  2018
1  Вася  200       3                  2020
2  Галя   21       2                   200


In [146]:
# ЗАВДАННЯ 3.3: виправити 'рік завершення школи' з 200 на 2020
df.at[2, "рік завершення школи"] = 2020
print(df)

   ім'я  вік рейтинг  рік завершення школи
0  Петя   22      10                  2018
1  Вася  200       3                  2020
2  Галя   21       2                  2020


In [147]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [148]:
# ЗАВДАННЯ 3.4: вивести з датасету `titanic` останні 10 записів 
titanic.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [149]:
# ЗАВДАННЯ 3.5: вибрати з датасету `titanic` рядки з пасажирами чоловічої статі віком 
# від 20 до 30 років, які подорожували 2 класом
titanic.loc[((titanic["Pclass"] == 2) & (titanic["Sex"] == "male"))]

PassengerId  Survived  Pclass                           Name   Sex   Age  \
17            18         1       2   Williams, Mr. Charles Eugene  male   NaN   
20            21         0       2           Fynney, Mr. Joseph J  male  35.0   
21            22         1       2          Beesley, Mr. Lawrence  male  34.0   
33            34         0       2          Wheadon, Mr. Edward H  male  66.0   
70            71         0       2     Jenkin, Mr. Stephen Curnow  male  32.0   
..           ...       ...     ...                            ...   ...   ...   
848          849         0       2              Harper, Rev. John  male  28.0   
861          862         0       2    Giles, Mr. Frederick Edward  male  21.0   
864          865         0       2         Gill, Mr. John William  male  24.0   
883          884         0       2  Banfield, Mr. Frederick James  male  28.0   
886          887         0       2          Montvila, Rev. Juozas  male  27.0   

     SibSp  Parch            Ticket  Fare Cabin Embarked  
17       0      0            244373  13.0   NaN        S  
20       0      0            239865  26.0   NaN        S  
21       0      0            248698  13.0   D56        S  
33       0      0        C.A. 24579  10.5   NaN        S  
70       0      0        C.A. 33111  10.5   NaN        S  
..     ...    ...               ...   ...   ...      ...  
848      0      1            248727  33.0   NaN        S  
861      1      0             28134  11.5   NaN        S  
864      0      0            233866  13.0   NaN        S  
883      0      0  C.A./SOTON 34068  10.5   NaN        S  
886      0      0            211536  13.0   NaN        S  

[108 rows x 12 columns]

In [159]:
# ЗАВДАННЯ 3.6: видалити з датасету `titanic` рядки з пасажирами у яких відсутня
# вартість (fare) квітка

titanic = titanic.loc[titanic["Fare"] != 0]
titanic


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[876 rows x 12 columns]

In [164]:
# ЗАВДАННЯ 3.7: підрахувати середню вартість квитка у каютах 1-го класу
avg_price = titanic[titanic["Pclass"] == 1]["Fare"].mean()
print(avg_price)

86.14887440758287


## 4. Агрегація датафреймів

__Агрегація__ - це функції отримання агрегованих даних шляхом групування об'єктів датафрейма 

### ПРИКЛАДИ

In [165]:
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [166]:
# підрахувати середній вік пасажирів по класам кают
group_by_class = titanic.groupby(["Pclass"])
avg_age = group_by_class["Age"].mean()
print(avg_age)

Pclass
1    38.220874
2    29.877630
3    25.059601
Name: Age, dtype: float64


In [167]:
# підрахувати кількість чоловіків та жінок по класам кают
man_woman_count = titanic.groupby(["Pclass", "Sex"])["Sex"].count()
man_woman_count

Pclass  Sex   
1       female     94
        male      117
2       female     76
        male      102
3       female    144
        male      343
Name: Sex, dtype: int64

In [168]:
# створити таблицю в якій підраховано середню вартість білетів (Fare) в залежності
# від місця посадки (Embarked) по класам кают
tickets_cost = titanic.pivot_table(values="Fare", index="Pclass", columns="Embarked",
                   aggfunc=np.mean)
tickets_cost

Embarked           C          Q          S
Pclass                                    
1         104.718529  90.000000  73.248668
2          25.358335  12.350000  21.099367
3          11.214083  11.183393  14.811923

### ЗАВДАННЯ

In [171]:
# ЗАВДАННЯ 4.1: отримати відомості про максимальний вік жінок та чоловіків
max_age =  titanic.pivot_table(values="Age", columns="Sex",
                   aggfunc=np.max)
print(max_age)

Sex  female  male
Age    63.0  80.0


___ЗАВДАННЯ 4.2___

на основі даних з `titanic` побудувати таблицю наступного вигляду:

Pclass  |Male  | Female
--------|------|-------
1  | ... | ...
2  | ... | ...
3  | ... | ...

де замість `...` повинно бути кількість виживших (Survived) чоловіків та жінок відповідно

In [178]:
surv_table = titanic.pivot_table(values="Survived", index="Pclass", columns="Sex",
                   aggfunc=np.sum)
surv_table

Sex     female  male
Pclass              
1           91    45
2           70    17
3           72    46